DROP TABLE IF EXISTS "FACT_Fight";

CREATE TABLE IF NOT EXISTS "FACT_Fight" (
    "FACT_Fight_Key"                                   SERIAL PRIMARY KEY,
    "FACT_Fight_Date_Key"                              VARCHAR(10),
    "FACT_Fight_Gender_Key"                            VARCHAR(10),
    "FACT_Fight_Weight_Class_Key"                      VARCHAR(100),
    "FACT_Fight_Title_Fight"                           BOOLEAN,
    "FACT_Fight_Result_Key"                            VARCHAR(100),
    "FACT_Fight_Method_Key"                            VARCHAR(100),
    "FACT_Fight_Round"                                 INTEGER,
    "FACT_Fight_Time"                                  VARCHAR(10),
    "FACT_Fight_Fight_Time_Format_Key"                 VARCHAR(100),
    "FACT_Fight_Duration_Mins"                         FLOAT,
    "FACT_Fight_Fighter_1_Key"                         VARCHAR(100),
    "FACT_Fight_Fighter_1_Knock_Downs"                 INTEGER,
    "FACT_Fight_Fighter_1_Sign.Strikes_Done"           INTEGER,
    "FACT_Fight_Fighter_1_Sign.Strikes_Attempted"      INTEGER,
    "FACT_Fight_Fighter_1_Sign.Strikes_Perc."          VARCHAR(100),
    "FACT_Fight_Fighter_1_Total_Strikes_Done"          INTEGER,
    "FACT_Fight_Fighter_1_Total_Strikes_Attempted"     INTEGER,
    "FACT_Fight_Fighter_1_Takedowns_Done"              INTEGER,
    "FACT_Fight_Fighter_1_Takedowns_Attempted"         INTEGER,
    "FACT_Fight_Fighter_1_Takedowns_Perc."             VARCHAR(100),
    "FACT_Fight_Fighter_1_Submission_Attempts"         INTEGER,
    "FACT_Fight_Fighter_1_Rev"                         INTEGER,
    "FACT_Fight_Fighter_1_Control"                     VARCHAR(100),
    "FACT_Fight_Fighter_2_Key"                         VARCHAR(100),
    "FACT_Fight_Fighter_2_Knock_Downs"                 INTEGER,
    "FACT_Fight_Fighter_2_Sign.Strikes_Done"           INTEGER,
    "FACT_Fight_Fighter_2_Sign.Strikes_Attempted"      INTEGER,
    "FACT_Fight_Fighter_2_Sign.Strikes_Perc."          VARCHAR(100),
    "FACT_Fight_Fighter_2_Total_Strikes_Done"          INTEGER,
    "FACT_Fight_Fighter_2_Total_Strikes_Attempted"     INTEGER,
    "FACT_Fight_Fighter_2_Takedowns_Done"              INTEGER,
    "FACT_Fight_Fighter_2_Takedowns_Attempted"         INTEGER,
    "FACT_Fight_Fighter_2_Takedowns_Perc."             VARCHAR(100),
    "FACT_Fight_Fighter_2_Submission_Attempts"         INTEGER,
    "FACT_Fight_Fighter_2_Rev"                         INTEGER,
    "FACT_Fight_Fighter_2_Control"                     VARCHAR(100),
    "__elt_loaded_at"                                  TIMESTAMP WITH TIME ZONE DEFAULT (TIMEZONE('utc', NOW()))
);