services:
  minio:
    image: minio/minio
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${MINIO_USERNAME}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001" --address ":9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 20

  create-buckets:
    image: minio/mc:latest
    container_name: mlflow-create-buckets
    depends_on:
      minio:
        condition: service_healthy
    entrypoint:
      - /bin/sh
      - -c
      - |
        mc alias set myminio "http://minio:9000" \
          "${MINIO_USERNAME}" "${MINIO_PASSWORD}"
        mc mb --ignore-existing "myminio/${MINIO_MLFLOW_BUCKET_NAME:-mlflow}"
        mc mb --ignore-existing "myminio/${MINIO_RAW_DATA_BUCKET_NAME:-crawleddata}"
        mc mb --ignore-existing "myminio/${MINIO_EVENT_CRAWL_LOGS_BUCKET_NAME:-eventcrawlinglogs}"
        mc mb --ignore-existing "myminio/${MINIO_FIGHTER_CRAWL_LOGS_BUCKET_NAME:-fightercrawlinglogs}"
        mc mb --ignore-existing "myminio/${MINIO_ML_TRAINING_DATA_BUCKET_NAME:-mltrainingdata}"
    restart: "no"

  postgres-1:
    image: postgres:17
    restart: on-failure
    container_name: ${DATA_WAREHOUSE_POSTGRES_DB_NAME}-postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATA_WAREHOUSE_POSTGRES_DB_NAME}
      - POSTGRES_USER=${DATA_WAREHOUSE_POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${DATA_WAREHOUSE_POSTGRES_PASSWORD}
    ports:
      - "${DATA_WAREHOUSE_POSTGRES_HOST_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: on-failure
    container_name: pgadmin
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json

  scrapy-server:
    image: flik007/scrapyd-server:latest
    depends_on:
      create-buckets:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      - MINIO_USERNAME=${MINIO_USERNAME}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
      - MINIO_RAW_DATA_BUCKET_NAME=${MINIO_RAW_DATA_BUCKET_NAME}
      - MINIO_EVENT_CRAWL_LOGS_BUCKET_NAME=${MINIO_EVENT_CRAWL_LOGS_BUCKET_NAME}
      - MINIO_FIGHTER_CRAWL_LOGS_BUCKET_NAME=${MINIO_FIGHTER_CRAWL_LOGS_BUCKET_NAME}
      - SCRAPYD_USERNAME=${SCRAPYD_USERNAME}
      - SCRAPYD_PASSWORD=${SCRAPYD_PASSWORD}
      - PYTHONPATH=/app/common:/app/scrapyd/project
    ports:
      - "${SCRAPYDWEB_PORT}:5000"
      - "${SCRAPYD_PORT}:6800"
    volumes:
      - scrapyd-config:/app/config
      - scrapyd:/app/scrapyd
      - ../project:/app/scrapyd/project
      - ../project/UFCStats_Crawlers/requirements.txt:/requirements.txt
      - ../src/common:/app/common

  processing-python:
    image: python:3.11-slim # Change to 3.12.11 because the scripts runs on Airflow
    working_dir: /workspace
    volumes:
      - ../src/processing:/workspace
      - ../src/sql:/workspace/sql/
      - pip-cache:/root/.cache/pip   # speed up pip installs
    depends_on:
      create-buckets:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      - MINIO_USERNAME=${MINIO_USERNAME}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
      - MINIO_RAW_DATA_BUCKET_NAME=${MINIO_RAW_DATA_BUCKET_NAME}
      - DATA_WAREHOUSE_POSTGRES_DB_NAME=${DATA_WAREHOUSE_POSTGRES_DB_NAME}
      - DATA_WAREHOUSE_POSTGRES_USERNAME=${DATA_WAREHOUSE_POSTGRES_USERNAME}
      - DATA_WAREHOUSE_POSTGRES_PASSWORD=${DATA_WAREHOUSE_POSTGRES_PASSWORD}
      - DATA_WAREHOUSE_POSTGRES_HOST_PORT=${DATA_WAREHOUSE_POSTGRES_HOST_PORT}
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/workspace
    entrypoint: /bin/sh -lc
    command: |
      'python -m pip install --upgrade pip &&
       if [ -f requirements.txt ]; then pip install -r requirements.txt; fi &&
       echo "Pybox ready. Sleeping..." &&
       tail -f /dev/null'
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import sys; sys.exit(0)'"]
      interval: 30s
      timeout: 5s
      retries: 3

  machine-learning-python:
    image: python:3.11-slim # Change to 3.12.11 because the scripts runs on Airflow
    working_dir: /workspace
    volumes:
      - ../src/machine_learning:/workspace
      - ../src/machine_learning/results:/workspace/results
      - pip-cache:/root/.cache/pip   # speed up pip installs
    depends_on:
      create-buckets:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      - DATA_WAREHOUSE_POSTGRES_DB_NAME=${DATA_WAREHOUSE_POSTGRES_DB_NAME}
      - DATA_WAREHOUSE_POSTGRES_USERNAME=${DATA_WAREHOUSE_POSTGRES_USERNAME}
      - DATA_WAREHOUSE_POSTGRES_PASSWORD=${DATA_WAREHOUSE_POSTGRES_PASSWORD}
      - DATA_WAREHOUSE_POSTGRES_HOST_PORT=${DATA_WAREHOUSE_POSTGRES_HOST_PORT}
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/workspace
    entrypoint: /bin/sh -lc
    command: |
      'python -m pip install --upgrade pip &&
       if [ -f requirements.txt ]; then pip install -r requirements.txt; fi &&
       echo "Pybox ready. Sleeping..." &&
       tail -f /dev/null'
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import sys; sys.exit(0)'"]
      interval: 30s
      timeout: 5s
      retries: 3

  postgres-2:
    image: postgres:15
    container_name: mlflow-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${MLFLOW_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${MLFLOW_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MLFLOW_POSTGRES_DB_NAME}
    volumes:
      - mlflow-pgdata:/var/lib/postgresql/data
    ports:
      - "${MLFLOW_POSTGRES_HOST_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MLFLOW_POSTGRES_USERNAME} -d ${MLFLOW_POSTGRES_DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 10

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow-server
    depends_on:
      postgres-2:
        condition: service_healthy
      minio:
        condition: service_healthy
      create-buckets:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      # Backend store URI built from vars
      MLFLOW_BACKEND_STORE_URI: ${MLFLOW_BACKEND_STORE_URI}

      # S3/MinIO settings
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
      MLFLOW_ARTIFACTS_DESTINATION: ${MLFLOW_ARTIFACTS_DESTINATION}
      AWS_ACCESS_KEY_ID: ${MINIO_USERNAME}
      AWS_SECRET_ACCESS_KEY: ${MINIO_PASSWORD}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      MLFLOW_S3_IGNORE_TLS: "true"

      # Server host/port
      MLFLOW_HOST: ${MLFLOW_HOST}
      MLFLOW_PORT: ${MLFLOW_PORT}

    command:
      - /bin/bash
      - -c
      - |
        pip install --no-cache-dir psycopg2-binary boto3
        mlflow server \
          --backend-store-uri "${MLFLOW_BACKEND_STORE_URI}" \
          --artifacts-destination "${MLFLOW_ARTIFACTS_DESTINATION}" \
          --serve-artifacts \
          --host "${MLFLOW_HOST}" \
          --port "${MLFLOW_PORT}"
    ports:
      - "${MLFLOW_PORT}:${MLFLOW_PORT}"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:${MLFLOW_PORT}/health')",
        ]
      interval: 10s
      timeout: 5s
      retries: 30

networks:
  default: # default keyword helps us not having to go to each service and attach them to this network
    name: ufc_infra_network

volumes:
  minio-data:
  postgres-data:
  mlflow-pgdata:
  pgadmin-data:
  scrapyd:
  scrapyd-config:
  pip-cache: