DROP TABLE IF EXISTS raw_fight_stats;

CREATE TABLE raw_fight_stats(
    "Fight_ID"                              SERIAL,
    "Date"                                  DATE,
    "Gender"                                VARCHAR(10),
    "Weight_Class"                          VARCHAR(100),
    "Title_Fight"                           BOOLEAN,
    "Result"                                VARCHAR(100),
    "Method"                                VARCHAR(100),
    "Round"                                 INTEGER,
    "Time"                                  VARCHAR(10),
    "Fight_Time_Format"                     VARCHAR(100),
    "Fighter_1_ID"                          VARCHAR(100),
    "Fighter_1_Name"                        VARCHAR(100),
    "Fighter_1_Nickname"                    VARCHAR(100),
    "Fighter_1_Knock_Downs"                 INTEGER,
    "Fighter_1_Sign.Strikes_Done"           INTEGER,
    "Fighter_1_Sign.Strikes_Attempted"      INTEGER,
    "Fighter_1_Sign.Strikes_Perc."          VARCHAR(100),
    "Fighter_1_Total_Strikes_Done"          INTEGER,
    "Fighter_1_Total_Strikes_Attempted"     INTEGER,
    "Fighter_1_Takedowns_Done"              INTEGER,
    "Fighter_1_Takedowns_Attempted"         INTEGER,
    "Fighter_1_Takedowns_Perc."             VARCHAR(100),
    "Fighter_1_Submission_Attempts"         INTEGER,
    "Fighter_1_Rev"                         INTEGER,
    "Fighter_1_Control"                     VARCHAR(100),
    "Fighter_2_ID"                          VARCHAR(100),
    "Fighter_2_Name"                        VARCHAR(100),
    "Fighter_2_Nickname"                    VARCHAR(100),
    "Fighter_2_Knock_Downs"                 INTEGER,
    "Fighter_2_Sign.Strikes_Done"           INTEGER,
    "Fighter_2_Sign.Strikes_Attempted"      INTEGER,
    "Fighter_2_Sign.Strikes_Perc."          VARCHAR(100),
    "Fighter_2_Total_Strikes_Done"          INTEGER,
    "Fighter_2_Total_Strikes_Attempted"     INTEGER,
    "Fighter_2_Takedowns_Done"              INTEGER,
    "Fighter_2_Takedowns_Attempted"         INTEGER,
    "Fighter_2_Takedowns_Perc."             VARCHAR(100),
    "Fighter_2_Submission_Attempts"         INTEGER,
    "Fighter_2_Rev"                         INTEGER,
    "Fighter_2_Control"                     VARCHAR(100),
    "Duration_Mins"                         FLOAT,
    "__elt_loaded_at"                       TIMESTAMP WITH TIME ZONE DEFAULT (TIMEZONE('utc', NOW())),

    PRIMARY KEY("Fight_ID")
)