DROP TABLE IF EXISTS raw_fighters_stats_before_fight;

CREATE TABLE raw_fighters_stats_before_fight(
    "Fight_ID"                                  SERIAL,
    "Fighter_1_ID"                              VARCHAR(100),
    "Fighter_1_Name"                            VARCHAR(100),
    "Fighter_1_Nickname"                        VARCHAR(100),
    "Fighter_1_Age"                             INTEGER,
    "Fighter_1_Wins"                            INTEGER,
    "Fighter_1_Loses"                           INTEGER,
    "Fighter_1_Draws"                           INTEGER,
    "Fighter_1_Avg_Fight_Time_Mins"             FLOAT,
    "Fighter_1_Sign_Strikes_Landed_per_Min"     FLOAT,
    "Fighter_1_Striking_Accuracy"               FLOAT,
    "Fighter_1_Sign_Strikes_Absorbed_per_Min"   FLOAT,
    "Fighter_1_Striking_Defense"                FLOAT,
    "Fighter_1_Takedown_Average_per_15Min"      FLOAT,
    "Fighter_1_Takedown_Accuracy"               FLOAT,
    "Fighter_1_Takedown_Defense"                FLOAT,
    "Fighter_1_Submission_Average_per_15M"      FLOAT,
    "Fighter_2_ID"                              VARCHAR(100),
    "Fighter_2_Name"                            VARCHAR(100),
    "Fighter_2_Nickname"                        VARCHAR(100),
    "Fighter_2_Age"                             INTEGER,
    "Fighter_2_Wins"                            INTEGER,
    "Fighter_2_Loses"                           INTEGER,
    "Fighter_2_Draws"                           INTEGER,
    "Fighter_2_Avg_Fight_Time_Mins"             FLOAT,
    "Fighter_2_Sign_Strikes_Landed_per_Min"     FLOAT,
    "Fighter_2_Striking_Accuracy"               FLOAT,
    "Fighter_2_Sign_Strikes_Absorbed_per_Min"   FLOAT,
    "Fighter_2_Striking_Defense"                FLOAT,
    "Fighter_2_Takedown_Average_per_15Min"      FLOAT,
    "Fighter_2_Takedown_Accuracy"               FLOAT,
    "Fighter_2_Takedown_Defense"                FLOAT,
    "Fighter_2_Submission_Average_per_15M"      FLOAT,
    "__elt_loaded_at"                           TIMESTAMP WITH TIME ZONE DEFAULT (TIMEZONE('utc', NOW())),

    PRIMARY KEY("Fight_ID")
);