# Some special cases from domain knowledge
# TODO: SEE HOW TO STORE THEM
full_names_to_gender = {
    'Xie Bin':   'male',
    'Xiao Long': 'male',
    'Fazlo Mulabitinovic': 'male',
    'Kin Moy': 'male',
    'Gisele Moreira': 'female',
    'Aji Susilo': 'male',
    'Kaline Medeiros': 'female',
    'AJ McKee': 'male',
    'Lucasz Sudolski': 'male',
    'AJ Matthews': 'male',
    'Daijiro Matsui': 'male',
    'Waachiim Spiritwolf': 'male',
    'Poppies Martinez': 'male',
    'CJ Marsh': 'male',
    'Kestutis Smirnovas': 'male',
    'Yokthai Sithoar': 'male',
    'AJ Siscoe': 'male',
    'Kaleo Kwan': 'male',
    'Eldari Kurtanidze': 'male',
    'Rizvan Kuniev': 'male',
    'Jorgen Kruth': 'male',
    'Iouri Kotchkine': 'male',
    'Aliev Makhmud': 'male',
    'Klayton Mai': 'male',
    'Maheshate': 'male',
    'Lolohea Mahe': 'male',
    'Abus Magomedov': 'male',
    'Ibragim Magomedov': 'male',
    'Ilima Macfarlane': 'female',
    'Jansey Silva': 'male',
    'Siala Siliga': 'male',
    'Katsuyori Shibata': 'male',
    'Lv Zhenhong': 'male',
    'Sokun Koh': 'male',
    'Jong Man Kim': 'male',
    'Taiei Kin': 'male',
    'Jong Won Kim': 'male',
    'Min Soo Kim': 'male',
    'Jong Wang Kim': 'male',
    'Dae Won Kim': 'male',
    'Aliaskhab Khizriev': 'male',
    'Bu-Kyung Jung': 'male',
    'Jamelle Jones': 'male',
    'Roshaun Jones': 'male',
    'Deshaun Johnson': 'male',
    'Shang Zhifa': 'male',
    'Cleber Luciano': 'male',
    'Rashard Lovelace': 'male',
    'Mabelly Lima': 'female',
    'Mayana Kellem': 'female',
    'Ryo Kawamura': 'male',
    'Canaan Kawaihae': 'male',
    'Bubba Pugh': 'male',
    'Adrienna Jenkins': 'female',
    'Bubba Jenkins': 'male',
    'Gigo Jara': 'male',
    'Matheus Scheffel': 'male',
    'Lumumba Sayers': 'male',
    'Jeimeson Saudino': 'male',
    'Edivan Santos': 'male',
    'Marilia Santos': 'female',
    'Gleristone Santos': 'male',
    'Shaheen Santana': 'male',
    'Jae Suk Lim': 'male',
    'Chi Lewis-Parry': 'male',
    'Lukasz Les': 'male',
    'Cheyden Leialoha': 'male',
    'Ryuta Sakurai': 'male',
    'Thanh Le': 'male',
    'Chatt Lavender': 'male',
    'Yohan Lainesse': 'male',
    'Kemran Lachinov': 'male',
    'Leiticia Pestova': 'female',
    'Jerron Peoples': 'male',
    'Yusup Saadulaev': 'male',
    'Achmed Labasanov': 'male',
    'Jhonoven Pati': 'male',
    'Cyrillo Padilha': 'male',
    'Casey Ryan': 'male',
    'Murilo Rua': 'male',
    'Kain Royer': 'male',
    'Hilarie Rose': 'female',
    'Jonatas Novaes': 'male',
    'Talita Nogueira': 'female',
    'Chidi Njokuani': 'male',
    'Soichi Nishida': 'male',
    'Khomkrit Niimi': 'male',
    'Jaimelene Nievera': 'female',
    'Shungo Oyama': 'male',
    'Kleydson Rodrigues': 'male',
    'Damonte Robinson': 'male',
    'Nasrudin Nasrudinov': 'male',
    'Andrews Nakahara': 'male',
    'Yukiya Naito': 'male',
    'Chibwikem Onyenegecha': 'male',
    'Gadzhi Omargadzhiev': 'male',
    'Casey Olson': 'male',
    'JJ Okanovich': 'male',
    'Michiyoshi Ohara': 'male',
    'Nicdali Rivera-Calanoc': 'female',
    'Vitor Ribeiro': 'male',
    'Iony Razafiarison': 'female',
    'Raou Raou': 'male',
    'JW Wright': 'male',
    'Qiu Lun': 'male',
    'Xue Do Won': 'male',
    'Maimaiti Tuohati': 'male',
    'Teila Tuli': 'male',
    'Blair Tugman': 'male',
    'Dimitiri Wanderley': 'male',
    'Treston Thomison': 'male',
    'Taneisha Tennant': 'female',
    'Ewerton Teixeira': 'male',
    'J.T Taylor': 'male',
    'Junior Tafa': 'male',
    'Milco Voorn': 'male',
    'DeMarco Villalona': 'male',
    'Vitor Vianna': 'male',
    'Jerrel Venetiaan': 'male',
    'Han Ten Yun': 'male',
    'Trenell Young': 'male',
    'Artenus Young': 'male',
    'Dong Sik Yoon': 'male',
    'Sanghoon Yoo': 'male',
    'Goiti Yamauchi': 'male',
    'Ryuki Ueyama': 'male',
    'Zhang Minyang': 'male',
    'Joao Zaiden': 'male',
    'Gleidson Cutis': 'male',
    'Pat Curran': 'male',
    'Luiz Azeredo': 'male',
    'Javy Ayala': 'male',
    'Bazigit Atajev': 'male',
    'Khusein Askhabov': 'male',
    'Chalid Arrab': 'male',
    'JJ Ambrose': 'male',
    'Maiara Amanajas dos Santos': 'female',
    'Estefani Almeida': 'female',
    'Jailton Almeida': 'male',
    'Javi Alanis': 'male',
    'Herdem Alacabek': 'male',
    'Nikk Covert': 'male',
    'JR Coughran': 'male',
    'Jadson Costa': 'male',
    'TJ Cook': 'male',
    'Cortez Coleman': 'male',
    'Coltin Cole': 'male',
    'RJ Clifford': 'male',
    'Mychal Clark': 'male',
    'Hong Man Choi': 'male',
    'Mu Bae Choi': 'male',
    'Gesias Cavalcante': 'male',
    'Bendy Casimir': 'male',
    'Dos Caras Jr.': 'male',
    'Goldman Butler': 'male',
    'Lukasz Brzeski': 'male',
    'Antwain Britt': 'male',
    'Colley Bradford': 'male',
    'Ashe Bowman': 'male',
    'Kyron Bowen': 'male',
    'Francois Botha': 'male',
    'Calen Born': 'male',
    'Kotetsu Boku': 'male',
    'Sherrard Blackledge': 'male',
    'Khadzhi Bestaev': 'male',
    'Pat Benson': 'male',
    'Shonte Barnes': 'male',
    'Junior Barata': 'male',
    'Yohan Banks': 'male',
    'Neiman Gracie': 'male',
    'Ralek Gracie': 'male',
    'Royler Gracie': 'male',
    'Crosley Gracie': 'male',
    'Rickson Gracie': 'male',
    'Tresean Gore': 'male',
    'Tebaris Gordon': 'male',
    'Kier Gooch': 'male',
    'Mikey Gonzalez': 'male',
    'Krishaun Gilmore': 'male',
    'Kultar Gill': 'male',
    'Rulon Gardner': 'male',
    'Fernie Garcia': 'male',
    'Turrell Galloway': 'male',
    'Zelg Galesic': 'male',
    'Alavutdin Gadjiev': 'male',
    'Rilley Dutro': 'male',
    'OJ Dominguez': 'male',
    'AJ Dobson': 'male',
    'Abongo Humphrey': 'male',
    'Casey Huffman': 'male',
    'Blood Diamond': 'male',
    'Jamey-Lyn Horth': 'male',
    'Kailan Hill': 'male',
    'Crezio de Souza': 'male',
    'Johil de Oliveira': 'male',
    'Lemont Davis': 'male',
    'LC Davis': 'male',
    'TJ Hepburn': 'male',
    'Gerric Hayes': 'male',
    'Dhafir Harris': 'male',
    'Baru Harn': 'male',
    'CJ Hamilton': 'male',
    'Yazan Hajeh': 'male',
    'Achilles Estremadura': 'male',
    'Pro Escobedo': 'male',
    'Chel Erwin-Davis': 'male',
    'Sovannahry Em': 'male',
    'Adli Edwards': 'male',
    'Donavon Frelow': 'male',
    'Patricky Freire': 'male',
    'Codale Ford': 'male',
    'Claudionor Fontinelle': 'male',
    'Mal Foki': 'male',
    'AJ Fonseca': 'male',
    'AJ Fletcher': 'male',
    'Isi Fitikefu': 'male',
    'Luiz Firmino': 'male',
    'Erisson Ferreira da Silva': 'male',
    'Bibiano Fernandes': 'male',
    'Rhadi Ferguson': 'male',
    'JP Felty': 'male',
    'Joao Paulo Faria': 'male',
    'Wagnney Fabiano': 'male',
    'Tokimitsu Ishizawa': 'male',
    'Egan Inoue': 'male',
    'Seichi Ikemoto': 'male',
    'Tatsuro Taira': 'male',
    'Ren Ozaki': 'male',
    'Adilet Nurmatov': 'male',
    'Joilton Lutterbach': 'male',
    'In Su Hwang': 'male',
    'Huang Feier': 'male',
    'Yuele Huang': 'male',
    'JunYoung Hong': 'male',
    'SeongChan Hong': 'male',
    'An Tuan Ho': 'male',
    'Donavon Hedrick': 'male',
    'Shin Haraguchi': 'male',
    'Lu Zhengyong': 'male',
    'Lu Kai': 'male',
    'Li Yunfeng': 'male',
    'Macksom Lee': 'male',
    'Sulangrangbo': 'male',
    'Chungreng Koren': 'male',
    'Top Noi Kiwram': 'male',
    'So Yul Kim': 'female',
    'KyuSung Kim': 'male',
    'Sangwook Kim': 'male',
    'HanSeul Kim': 'male',
    'MinWoo Kim': 'male',
    'WonBin Ki': 'male',
    'KyeungPyo Kim': 'male',
    'Mansher Khera': 'male',
    'Maimaitituoheti Keremuaili': 'male',
    'Losene Keita': 'male',
    'Masuto Kawana': 'male',
    'Jinnosuke Kashimura': 'male',
    'Koya Kanda': 'male',
    'Shuya Kamikubo': 'male',
    'Shah Kamali': 'male',
    'Kaiwen': 'male',
    'Heraldo Souza': 'male',
    'Hecher Sosa': 'male',
    'Hyeonjong Song': 'male',
    'Jeremia Siregar': 'male',
    'Sim Kai Xiong': 'male',
    'Jhonata Silva': 'male',
    'Janaina Silva': 'female',
    'Ronal Siahaan': 'male',
    'YeDam Seo': 'male',
    'Demba Seck': 'male',
    'Neemias Santana': 'male',
    'Mridul Saikia': 'male',
    'Saygid Izagakhmaev': 'male',
    'Kuya Ito': 'male',
    'Jacobi Jones': 'male',
    'Jinensibieke Asikeerbai': 'male',
    'Jiniushiyue': 'male',
    'YunSeong Jang': 'male',
    'Samandar Murodov': 'male',
    'Ailiya Muratbek': 'male',
    'Ananias Mulumba': 'male',
    'Bia Mesquita': 'female',
    'Nair Melikyan': 'male',
    'Koyomi Matsushima': 'male',
    'Toki Matsui': 'male',
    'Islem Masraf': 'male',
    'Dom Mar Fan': 'male',
    'Nayara Maia': 'female',
    'Murtazali Magomedov': 'male',
    'Nghiem Van Y': 'male',
    'Mandel Nallo': 'male',
    'Tokitaka Nakanishi': 'male',
    'Quemuel Ottoni': 'male',
    'Pat Pytlik': 'male',
    'Windri Patilima': 'male',
    'EoJin Park': 'male',
    'Ruel Panales': 'male',
    'Mashrabjon Ruzibaev': 'male',
    'Kaleio Romero': 'male',
    'Shaqueme Rock': 'male',
    'Haisam Rida': 'male',
    'Ren Yawei': 'male',
    'Justice Torres': 'male',
    'Ti Haitao': 'male',
    'Otari Tanzilovi': 'male',
    'ChangMin Yoon': 'male',
    'Yin Shuai': 'male',
    'Yibugele': 'male',
    'Wuziazibieke Jiahefu': 'male',
    'Kwon Wonil': 'male',
    'Brahyam Zurcher': 'male',
    'Zhu Kangjie': 'male',
    'Zhou Kun': 'male',
    'Daermisi Zhawupasi': 'male',
    'Zhang Zhenyang': 'male',
    'Zhang Qinghe': 'male',
    'Rickson Zenidim': 'male',
    'Junye Gao': 'male',
    'Shanelle Dyer': 'female',
    'Asjabharan': 'male',
    'Vanilto Antunes': 'male',
    'Angga': 'male',
    'Fellipe Andrew': 'male',
    'Mahamed Aly': 'male',
    'Ashiek Ajim': 'male',
    'Ahejiang Ailinuer': 'male',
    'Agulali': 'male',
    'Kantharaj Agasa': 'male',
    'Cyborg Abreu': 'male',
    'Kaik Brito': 'male',
    'Chasen Blair': 'male',
    'Davi Bittencourt': 'male',
    'Angad Bisht': 'male',
    'Yousri Belgaroui': 'male',
    'Namsrai Batbayar': 'male',
    'Djani Barbir': 'male',
    'Iwo Baraniewski': 'male',
    'Balajin': 'male',
    'Bahatebole Batebolati': 'male',
    'Lerryan Douglas': 'male',
    'Dong Huaxiang': 'male',
    'Ding Meng': 'male',
    'Wallen Del Rosario': 'male',
    'Anvarbek Daniyalbekov': 'male',
    'Deni Daffa': 'male',
    'Radley Da Silva': 'male',
    'Raheam Forest': 'male',
    'Erisson Ferreira': 'male',
    'Feng Pengchao': 'male',
    'Joao Elias': 'male',
    'Roybert Echeverria': 'male',
    'Vitor Costa': 'male',
    'Willian Colorado': 'male',
    'Jeisla Chaves': 'female',
    'Mando Gutierrez': 'male',
    'Gugun Gusman': 'male',
    'Rainn Guerrero': 'male',
    'Eperaim Ginting': 'male',
}
