DROP TABLE IF EXISTS "DIM_Weight_Class" CASCADE;

-- TODO: MAYBE ADD A COLUMN THAT SAYS THE LOWER AND UPPER LIMIT
-- AND HAVE IT AS A SEED TABLE
CREATE TABLE IF NOT EXISTS "DIM_Weight_Class" (
    "DIM_Weight_Class_Key"     SERIAL PRIMARY KEY,
    "DIM_Weight_Class_Name"    VARCHAR(100) NOT NULL,
    "__elt_loaded_at"          TIMESTAMP WITH TIME ZONE DEFAULT (TIMEZONE('utc', NOW()))
);